"""enum ultilizado

Revision ID: 7226785aafeb
Revises: 2ad94a3be9ab
Create Date: 2022-04-26 09:46:05.137553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7226785aafeb'
down_revision = '2ad94a3be9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('one', 'two', 'three', name='values'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'level',
               existing_type=sa.Enum('one', 'two', 'three', name='values'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
