"""skill model atualized

Revision ID: 8a26225928bc
Revises: 719c1c89478a
Create Date: 2022-04-27 10:55:56.625711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a26225928bc'
down_revision = '719c1c89478a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('skills_skill_key', 'skills', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('skills_skill_key', 'skills', ['skill'])
    # ### end Alembic commands ###
